#!/bin/busybox sh
set -eu
case "$1" in
  bound|renew)
    ip addr flush dev "$interface"
    ip addr add "$ip/${subnet:-255.255.255.0}" dev "$interface"
    ip route flush dev "$interface"
    for gateway in $router; do ip route add default via "$gateway" dev "$interface"; break; done
    ;;
esac
