#!/bin/busybox sh
set -eu
case "$1" in
  bound|renew)
    ip addr flush dev "$interface"
    prefix=$(/bin/busybox ipcalc -p "$ip" "${subnet:-255.255.255.0}")
    ip addr add "$ip/${prefix#PREFIX=}" dev "$interface"
    ip route flush dev "$interface"
    for gateway in $router; do ip route add default via "$gateway" dev "$interface"; break; done
    ;;
esac
